apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myfirstreplicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-tknika
    matchExpressions:
    - key: app
      operator: In
      values:
      - nginx-tknika
  template:
    metadata:
      labels:
        app: nginx-tknika
    spec:
      volumes:  
      - name: myfirstvolume
        emptyDir: {}
      containers:
      - name: myfirstcontainer
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: myfirstvolume
      - name: contenido
        image: ubuntu
        command: ["/bin/sh"]
        args: ["-c", "echo Kaixo Tknikatik > /data/index.html && tail -f /dev/null"]
        volumeMounts:
        - mountPath: /data
          name: myfirstvolume