apiVersion: v1
kind: Pod
metadata:
  name: myfirstpod
spec:
  volumes:
  - name: myfirstvolume
    emptyDir: {}
  containers:
  - name: myfirstcontainer
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: myfirstvolume
      mountPath: /usr/share/nginx/html
  - name: mysecondcontainer
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: root
    ports:
      - containerPort: 3306