apiVersion: v1
kind: Pod
metadata:
  name: myfirstpod
  labels:
    app: myfirstpod
spec:
  volumes:  
  - name: myfirstvolume
    emptyDir: {}
  containers:
  - name: myfirstcontainer
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: myfirstvolume
  - name: contenido
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "echo Kaixo Tknikatik > /data/index.html && tail -f /dev/null"]
    volumeMounts:
    - mountPath: /data
      name: myfirstvolume


  